on:
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'vendor/**'
      - 'Makefile'
      - 'Dockerfile'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.30.0'
      - name: check go mod and vendor are up-to-date
        run: |
          go mod tidy -diff
          go mod verify
          sqlc diff
      - run: make build VERSION=${{ github.ref_name }}
      - run: make test
      # - uses: shogo82148/actions-goveralls@v1
      #   with:
      #     path-to-profile: coverage.txt
      - run: make clean

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.5
      - run: go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...
      - run: go run golang.org/x/tools/cmd/deadcode@latest -test ./...
